sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Gjz_13144
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com  # 根据实际创建的地域填写
    access-key-id: ${ALIOSS_ACCESS_KEY_ID}      # 替换为你的AccessKey ID
    access-key-secret:  ${ALIOSS_ACCESS_KEY_SECRET}
    bucket-name: ${ALIOSS_BUCKET_NAME}       # 替换为你的Bucket名称
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: ${WECHAT_APP_ID}
    secret: ${WECHAT_APP_SECRET}
    mchid: xxxxxx  # 商户号
    mchSerialNo: xxxxxx # 商户API证书的证书序列号
    privateKeyFilePath: xxxxxx # 商户私钥文件路径
    apiV3Key: xxxxxx # APIv3密钥
    wechatPayCertFilePath: xxxxxx # 微信支付平台证书文件路径
    notifyUrl: xxxxxx # 微信支付结果回调地址
    mchCertSerialNo: xxxxxx # 商户证书序列号
  shop:
    address: 福建省漳州市龙海区顺德五香卤面（总店）
  baidu:
    ak: MOK4IqU6HCmWFmRNCABwnNmG4djc7UpG
  rabbitmq:
    host: localhost        # RabbitMQ 服务器地址
    port: 5672             # 默认端口
    username: guest        # 用户名 (生产环境请务必修改)
    password: guest        # 密码
    virtual-host: /        # 虚拟主机 (隔离环境)
    # 可选配置：开启发送确认机制，确保消息到达交换机
    publisher-confirm-type: correlated
    # 可选配置：开启发送返回机制，确保消息路由到队列
    publisher-returns: true
    listener:
      # 可选配置：设置同一时刻最多投递给消费者一条消息
     prefetch: 1 #每次只能获取一条消息，处理完成后才能获取下一个消息